import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import '@mui/material-pigment-css/styles.css'
import { DefaultPropsProvider } from '@/components/default-props-provider'
import { NavBar } from '@/components/nav-bar'
import Footer from '@/components/footer'
import { CssBaseline } from '@/components/css-baseline'
import type { Theme, SxProps } from '@mui/material/styles'

import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from '@/utilities/theme'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { UsaStateProvider } from '@/hooks/use-usa-state'

declare module 'react' {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface HTMLAttributes<T> {
    sx?: SxProps<Theme>
  }
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface SVGProps<T> {
    sx?: SxProps<Theme>
  }
}
declare module '@mui/material-pigment-css' {
  interface ThemeArgs {
    theme: Theme
  }
}

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        id="__next"
        className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <DefaultPropsProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <UsaStateProvider>
                <NavBar />
                {children}
                <Footer />
              </UsaStateProvider>
            </ThemeProvider>
          </DefaultPropsProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
