// Please parse this html table and extract the details about four fields for each row in the table: 'districtName', 'leaderName', 'leaderURL', and 'dateElected'.  Provide the information in a JSON array.

export const indianaStateSenate = [
  {
    districtName: 'Indiana State Senate District 1',
    leaderName: 'Dan Dernulc',
    leaderURL: 'https://ballotpedia.org/Dan_Dernulc',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 2',
    leaderName: 'Lonnie Randolph',
    leaderURL: 'https://ballotpedia.org/Lonnie_Randolph',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana State Senate District 3',
    leaderName: 'Mark Spencer',
    leaderURL: 'https://ballotpedia.org/Mark_Spencer_(Indiana)',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana State Senate District 4',
    leaderName: 'Rodney Pol Jr.',
    leaderURL: 'https://ballotpedia.org/Rodney_Pol_Jr.',
    dateElected: 'November 1, 2021',
  },
  {
    districtName: 'Indiana State Senate District 5',
    leaderName: 'Ed Charbonneau',
    leaderURL: 'https://ballotpedia.org/Ed_Charbonneau',
    dateElected: '2007',
  },
  {
    districtName: 'Indiana State Senate District 6',
    leaderName: 'Rick Niemeyer',
    leaderURL: 'https://ballotpedia.org/Rick_Niemeyer',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana State Senate District 7',
    leaderName: 'Brian Buchanan',
    leaderURL: 'https://ballotpedia.org/Brian_Buchanan',
    dateElected: 'February 12, 2018',
  },
  {
    districtName: 'Indiana State Senate District 8',
    leaderName: 'Mike Bohacek',
    leaderURL: 'https://ballotpedia.org/Mike_Bohacek',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana State Senate District 9',
    leaderName: 'Ryan Mishler',
    leaderURL: 'https://ballotpedia.org/Ryan_Mishler',
    dateElected: '2004',
  },
  {
    districtName: 'Indiana State Senate District 10',
    leaderName: 'David Niezgodski',
    leaderURL: 'https://ballotpedia.org/David_Niezgodski',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana State Senate District 11',
    leaderName: 'Linda Rogers',
    leaderURL: 'https://ballotpedia.org/Linda_Rogers',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana State Senate District 12',
    leaderName: 'Blake Doriot',
    leaderURL: 'https://ballotpedia.org/Blake_Doriot',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana State Senate District 13',
    leaderName: 'Susan Glick',
    leaderURL: 'https://ballotpedia.org/Susan_Glick',
    dateElected: '2010',
  },
  {
    districtName: 'Indiana State Senate District 14',
    leaderName: 'Tyler Johnson',
    leaderURL: 'https://ballotpedia.org/Tyler_Johnson_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 15',
    leaderName: 'Liz Brown',
    leaderURL: 'https://ballotpedia.org/Liz_Brown',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana State Senate District 16',
    leaderName: 'Justin Busch',
    leaderURL: 'https://ballotpedia.org/Justin_Busch',
    dateElected: 'November 6, 2018',
  },
  {
    districtName: 'Indiana State Senate District 17',
    leaderName: 'Andy Zay',
    leaderURL: 'https://ballotpedia.org/Andy_Zay',
    dateElected: 'December 20, 2016',
  },
  {
    districtName: 'Indiana State Senate District 18',
    leaderName: 'Stacey Donato',
    leaderURL: 'https://ballotpedia.org/Stacey_Donato',
    dateElected: 'September 11, 2019',
  },
  {
    districtName: 'Indiana State Senate District 19',
    leaderName: 'Travis Holdman',
    leaderURL: 'https://ballotpedia.org/Travis_Holdman',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana State Senate District 20',
    leaderName: 'Scott Baldwin',
    leaderURL: 'https://ballotpedia.org/Scott_Baldwin',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana State Senate District 21',
    leaderName: 'James Buck',
    leaderURL: 'https://ballotpedia.org/James_Buck',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana State Senate District 22',
    leaderName: 'Ronnie Alting',
    leaderURL: 'https://ballotpedia.org/Ronnie_Alting',
    dateElected: '1998',
  },
  {
    districtName: 'Indiana State Senate District 23',
    leaderName: 'Spencer Deery',
    leaderURL: 'https://ballotpedia.org/Spencer_Deery',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 24',
    leaderName: 'Brett A. Clark',
    leaderURL: 'https://ballotpedia.org/Brett_A._Clark_(Indiana)',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana State Senate District 25',
    leaderName: 'Mike Gaskill',
    leaderURL: 'https://ballotpedia.org/Mike_Gaskill',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 26',
    leaderName: 'Scott Alexander',
    leaderURL: 'https://ballotpedia.org/Scott_Alexander_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 27',
    leaderName: 'Jeff Raatz',
    leaderURL: 'https://ballotpedia.org/Jeff_Raatz',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana State Senate District 28',
    leaderName: 'Michael Crider',
    leaderURL: 'https://ballotpedia.org/Michael_Crider',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana State Senate District 29',
    leaderName: 'J.D. Ford',
    leaderURL: 'https://ballotpedia.org/J.D._Ford',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana State Senate District 30',
    leaderName: 'Fady Qaddoura',
    leaderURL: 'https://ballotpedia.org/Fady_Qaddoura',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana State Senate District 31',
    leaderName: 'Kyle Walker',
    leaderURL: 'https://ballotpedia.org/Kyle_Walker_(Indiana)',
    dateElected: 'November 17, 2020',
  },
  {
    districtName: 'Indiana State Senate District 32',
    leaderName: 'Aaron Freeman',
    leaderURL: 'https://ballotpedia.org/Aaron_Freeman',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana State Senate District 33',
    leaderName: 'Greg Taylor',
    leaderURL: 'https://ballotpedia.org/Greg_Taylor_(Indiana)',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana State Senate District 34',
    leaderName: 'La Keisha Jackson',
    leaderURL: 'https://ballotpedia.org/La_Keisha_Jackson',
    dateElected: 'April 18, 2024',
  },
  {
    districtName: 'Indiana State Senate District 35',
    leaderName: 'Michael Young',
    leaderURL: 'https://ballotpedia.org/R._Michael_Young_(Indiana)',
    dateElected: '2000',
  },
  {
    districtName: 'Indiana State Senate District 36',
    leaderName: 'Cyndi Carrasco',
    leaderURL: 'https://ballotpedia.org/Cyndi_Carrasco',
    dateElected: 'November 1, 2023',
  },
  {
    districtName: 'Indiana State Senate District 37',
    leaderName: 'Rodric D. Bray',
    leaderURL: 'https://ballotpedia.org/Rodric_D._Bray',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana State Senate District 38',
    leaderName: 'Greg Goode',
    leaderURL: 'https://ballotpedia.org/Greg_Goode_(Indiana)',
    dateElected: 'November 1, 2023',
  },
  {
    districtName: 'Indiana State Senate District 39',
    leaderName: 'Eric Bassler',
    leaderURL: 'https://ballotpedia.org/Eric_Bassler',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana State Senate District 40',
    leaderName: 'Shelli Yoder',
    leaderURL: 'https://ballotpedia.org/Shelli_Yoder',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana State Senate District 41',
    leaderName: 'Greg Walker',
    leaderURL: 'https://ballotpedia.org/Greg_Walker',
    dateElected: '2006',
  },
  {
    districtName: 'Indiana State Senate District 42',
    leaderName: 'Jean Leising',
    leaderURL: 'https://ballotpedia.org/Jean_Leising',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana State Senate District 43',
    leaderName: 'Randy Maxwell',
    leaderURL: 'https://ballotpedia.org/Randy_Maxwell',
    dateElected: 'September 28, 2023',
  },
  {
    districtName: 'Indiana State Senate District 44',
    leaderName: 'Eric Koch',
    leaderURL: 'https://ballotpedia.org/Eric_Koch',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana State Senate District 45',
    leaderName: 'Chris Garten',
    leaderURL: 'https://ballotpedia.org/Chris_Garten',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana State Senate District 46',
    leaderName: 'Andrea Hunley',
    leaderURL: 'https://ballotpedia.org/Andrea_Hunley',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana State Senate District 47',
    leaderName: 'Gary Byrne',
    leaderURL: 'https://ballotpedia.org/Gary_Byrne',
    dateElected: 'February 14, 2022',
  },
  {
    districtName: 'Indiana State Senate District 48',
    leaderName: 'Daryl Schmitt',
    leaderURL: 'https://ballotpedia.org/Daryl_Schmitt',
    dateElected: 'September 10, 2024',
  },
  {
    districtName: 'Indiana State Senate District 49',
    leaderName: 'Jim Tomes',
    leaderURL: 'https://ballotpedia.org/Jim_Tomes',
    dateElected: '2010',
  },
  {
    districtName: 'Indiana State Senate District 50',
    leaderName: 'Vaneta Becker',
    leaderURL: 'https://ballotpedia.org/Vaneta_Becker',
    dateElected: '2005',
  },
]

export const indianaHouseOfRepresentatives = [
  {
    districtName: 'Indiana House of Representatives District 1',
    leaderName: 'Carolyn Jackson',
    leaderURL: 'https://ballotpedia.org/Carolyn_Jackson',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 2',
    leaderName: 'Earl Harris, Jr.',
    leaderURL: 'https://ballotpedia.org/Earl_Harris,_Jr.',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 3',
    leaderName: 'Ragen Hatcher',
    leaderURL: 'https://ballotpedia.org/Ragen_Hatcher',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 4',
    leaderName: 'Edmond Soliday',
    leaderURL: 'https://ballotpedia.org/Edmond_Soliday',
    dateElected: '2006',
  },
  {
    districtName: 'Indiana House of Representatives District 5',
    leaderName: 'Dale DeVon',
    leaderURL: 'https://ballotpedia.org/Dale_DeVon',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 6',
    leaderName: 'Maureen Bauer',
    leaderURL: 'https://ballotpedia.org/Maureen_Bauer',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 7',
    leaderName: 'Jake Teshka',
    leaderURL: 'https://ballotpedia.org/Jake_Teshka',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 8',
    leaderName: 'Ryan Dvorak',
    leaderURL: 'https://ballotpedia.org/Ryan_Dvorak',
    dateElected: '2002',
  },
  {
    districtName: 'Indiana House of Representatives District 9',
    leaderName: 'Patricia Boy',
    leaderURL: 'https://ballotpedia.org/Patricia_Boy',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 10',
    leaderName: 'Charles Moseley',
    leaderURL: 'https://ballotpedia.org/Charles_Moseley',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 11',
    leaderName: 'Michael J. Aylesworth',
    leaderURL: 'https://ballotpedia.org/Michael_J._Aylesworth',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana House of Representatives District 12',
    leaderName: 'Mike Andrade',
    leaderURL: 'https://ballotpedia.org/Mike_Andrade',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 13',
    leaderName: 'Matt Commons',
    leaderURL: 'https://ballotpedia.org/Matt_Commons',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 14',
    leaderName: 'Vernon Smith',
    leaderURL: 'https://ballotpedia.org/Vernon_Smith',
    dateElected: '1990',
  },
  {
    districtName: 'Indiana House of Representatives District 15',
    leaderName: 'Harold Slager',
    leaderURL: 'https://ballotpedia.org/Harold_Slager',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 16',
    leaderName: 'Kendell Culp',
    leaderURL: 'https://ballotpedia.org/Kendell_Culp',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 17',
    leaderName: 'Jack Jordan',
    leaderURL: 'https://ballotpedia.org/Jack_Jordan',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 18',
    leaderName: 'David Abbott',
    leaderURL: 'https://ballotpedia.org/David_Abbott_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 19',
    leaderName: 'Julie Olthoff',
    leaderURL: 'https://ballotpedia.org/Julie_Olthoff',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 20',
    leaderName: 'Jim Pressel',
    leaderURL: 'https://ballotpedia.org/Jim_Pressel',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 21',
    leaderName: 'Timothy Wesco',
    leaderURL: 'https://ballotpedia.org/Timothy_Wesco',
    dateElected: '2010',
  },
  {
    districtName: 'Indiana House of Representatives District 22',
    leaderName: 'Craig Snow',
    leaderURL: 'https://ballotpedia.org/Craig_Snow',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 23',
    leaderName: 'Ethan Manning',
    leaderURL: 'https://ballotpedia.org/Ethan_Manning',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 24',
    leaderName: 'Hunter Smith',
    leaderURL: 'https://ballotpedia.org/Hunter_Smith_(Indiana)',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 25',
    leaderName: 'Becky Cash',
    leaderURL: 'https://ballotpedia.org/Becky_Cash',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 26',
    leaderName: 'Chris Campbell',
    leaderURL: 'https://ballotpedia.org/Chris_Campbell',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 27',
    leaderName: 'Sheila Ann Klinker',
    leaderURL: 'https://ballotpedia.org/Sheila_Ann_Klinker',
    dateElected: '1982',
  },
  {
    districtName: 'Indiana House of Representatives District 28',
    leaderName: 'Jeffrey Thompson',
    leaderURL: 'https://ballotpedia.org/Jeffrey_Thompson_(Indiana)',
    dateElected: '1998',
  },
  {
    districtName: 'Indiana House of Representatives District 29',
    leaderName: 'Alaina Shonkwiler',
    leaderURL: 'https://ballotpedia.org/Alaina_Shonkwiler',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 30',
    leaderName: 'Michael Karickhoff',
    leaderURL: 'https://ballotpedia.org/Michael_Karickhoff',
    dateElected: '2010',
  },
  {
    districtName: 'Indiana House of Representatives District 31',
    leaderName: 'Lori Goss-Reaves',
    leaderURL: 'https://ballotpedia.org/Lori_Goss-Reaves',
    dateElected: 'May 31, 2023',
  },
  {
    districtName: 'Indiana House of Representatives District 32',
    leaderName: 'Victoria Garcia Wilburn',
    leaderURL: 'https://ballotpedia.org/Victoria_Garcia_Wilburn',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 33',
    leaderName: 'John Prescott',
    leaderURL: 'https://ballotpedia.org/John_Prescott',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 34',
    leaderName: 'Sue Errington',
    leaderURL: 'https://ballotpedia.org/Sue_Errington',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 35',
    leaderName: 'Elizabeth Rowray',
    leaderURL: 'https://ballotpedia.org/Elizabeth_Rowray',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 36',
    leaderName: 'Kyle Pierce',
    leaderURL: 'https://ballotpedia.org/Kyle_Pierce_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 37',
    leaderName: 'Todd Huston',
    leaderURL: 'https://ballotpedia.org/Todd_Huston',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 38',
    leaderName: 'Heath VanNatter',
    leaderURL: 'https://ballotpedia.org/Heath_VanNatter',
    dateElected: '2010',
  },
  {
    districtName: 'Indiana House of Representatives District 39',
    leaderName: 'Daniel Lopez',
    leaderURL: 'https://ballotpedia.org/Daniel_Lopez_(Indiana)',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 40',
    leaderName: 'Gregory Steuerwald',
    leaderURL: 'https://ballotpedia.org/Gregory_Steuerwald',
    dateElected: '2007',
  },
  {
    districtName: 'Indiana House of Representatives District 41',
    leaderName: 'Mark Genda',
    leaderURL: 'https://ballotpedia.org/Mark_Genda',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 42',
    leaderName: 'Tim Yocum',
    leaderURL: 'https://ballotpedia.org/Tim_Yocum',
    dateElected: 'January 16, 2025',
  },
  {
    districtName: 'Indiana House of Representatives District 43',
    leaderName: 'Tonya Pfaff',
    leaderURL: 'https://ballotpedia.org/Tonya_Pfaff',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 44',
    leaderName: 'Beau Baird',
    leaderURL: 'https://ballotpedia.org/Beau_Baird',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 45',
    leaderName: 'Bruce Borders',
    leaderURL: 'https://ballotpedia.org/Bruce_Borders',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana House of Representatives District 46',
    leaderName: 'Bob Heaton',
    leaderURL: 'https://ballotpedia.org/Bob_Heaton',
    dateElected: 'November 3, 2010',
  },
  {
    districtName: 'Indiana House of Representatives District 47',
    leaderName: 'Robb Greene',
    leaderURL: 'https://ballotpedia.org/Robb_Greene',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 48',
    leaderName: 'Doug Miller',
    leaderURL: 'https://ballotpedia.org/Doug_Miller_(Indiana)',
    dateElected: 'November 5, 2014',
  },
  {
    districtName: 'Indiana House of Representatives District 49',
    leaderName: 'Joanna King',
    leaderURL: 'https://ballotpedia.org/Joanna_King',
    dateElected: 'December 21, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 50',
    leaderName: 'Lorissa Sweet',
    leaderURL: 'https://ballotpedia.org/Lorissa_Sweet',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 51',
    leaderName: 'Tony Isa',
    leaderURL: 'https://ballotpedia.org/Tony_Isa',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 52',
    leaderName: 'Ben Smaltz',
    leaderURL: 'https://ballotpedia.org/Ben_Smaltz',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 53',
    leaderName: 'Ethan Lawson',
    leaderURL: 'https://ballotpedia.org/Ethan_Lawson',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 54',
    leaderName: 'Cory Criswell',
    leaderURL: 'https://ballotpedia.org/Cory_Criswell',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 55',
    leaderName: 'Lindsay Patterson',
    leaderURL: 'https://ballotpedia.org/Lindsay_Patterson',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 56',
    leaderName: 'Bradford Barrett',
    leaderURL: 'https://ballotpedia.org/Bradford_Barrett',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 57',
    leaderName: 'Craig Haggard',
    leaderURL: 'https://ballotpedia.org/Craig_Haggard',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 58',
    leaderName: 'Michelle Davis',
    leaderURL: 'https://ballotpedia.org/Michelle_Davis_(Indiana)',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 59',
    leaderName: 'Ryan Lauer',
    leaderURL: 'https://ballotpedia.org/Ryan_Lauer',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 60',
    leaderName: 'Peggy Mayfield',
    leaderURL: 'https://ballotpedia.org/Peggy_Mayfield',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 61',
    leaderName: 'Matt Pierce',
    leaderURL: 'https://ballotpedia.org/Matt_Pierce_(Indiana)',
    dateElected: '2002',
  },
  {
    districtName: 'Indiana House of Representatives District 62',
    leaderName: 'Dave Hall',
    leaderURL: 'https://ballotpedia.org/Dave_Hall_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 63',
    leaderName: 'Shane Lindauer',
    leaderURL: 'https://ballotpedia.org/Shane_Lindauer',
    dateElected: 'November 16, 2017',
  },
  {
    districtName: 'Indiana House of Representatives District 64',
    leaderName: 'Matt Hostettler',
    leaderURL: 'https://ballotpedia.org/Matt_Hostettler',
    dateElected: 'November 7, 2018',
  },
  {
    districtName: 'Indiana House of Representatives District 65',
    leaderName: 'Christopher May',
    leaderURL: 'https://ballotpedia.org/Christopher_May',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 66',
    leaderName: 'Zach Payne',
    leaderURL: 'https://ballotpedia.org/Zach_Payne',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 67',
    leaderName: 'Alex Zimmerman',
    leaderURL: 'https://ballotpedia.org/Alex_Zimmerman',
    dateElected: 'July 17, 2023',
  },
  {
    districtName: 'Indiana House of Representatives District 68',
    leaderName: 'Garrett Bascom',
    leaderURL: 'https://ballotpedia.org/Garrett_Bascom',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 69',
    leaderName: 'Jim Lucas',
    leaderURL: 'https://ballotpedia.org/Jim_Lucas',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 70',
    leaderName: 'Karen Engleman',
    leaderURL: 'https://ballotpedia.org/Karen_Engleman',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 71',
    leaderName: 'Wendy Dant Chesser',
    leaderURL: 'https://ballotpedia.org/Wendy_Dant_Chesser',
    dateElected: 'June 4, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 72',
    leaderName: 'Edward Clere',
    leaderURL: 'https://ballotpedia.org/Edward_Clere',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 73',
    leaderName: 'Jennifer Meltzer',
    leaderURL: 'https://ballotpedia.org/Jennifer_Meltzer',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 74',
    leaderName: 'Steve Bartels',
    leaderURL: 'https://ballotpedia.org/Steve_Bartels',
    dateElected: 'November 16, 2017',
  },
  {
    districtName: 'Indiana House of Representatives District 75',
    leaderName: 'Cindy Ledbetter',
    leaderURL: 'https://ballotpedia.org/Cindy_Ledbetter',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 76',
    leaderName: 'Wendy McNamara',
    leaderURL: 'https://ballotpedia.org/Wendy_McNamara',
    dateElected: 'November 3, 2010',
  },
  {
    districtName: 'Indiana House of Representatives District 77',
    leaderName: 'Alex Burton',
    leaderURL: 'https://ballotpedia.org/Alex_Burton',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 78',
    leaderName: "Tim O'Brien",
    leaderURL: "https://ballotpedia.org/Tim_O'Brien_(Indiana)",
    dateElected: 'March 30, 2021',
  },
  {
    districtName: 'Indiana House of Representatives District 79',
    leaderName: 'Matthew Lehman',
    leaderURL: 'https://ballotpedia.org/Matthew_Lehman_(Indiana)',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 80',
    leaderName: 'Phil GiaQuinta',
    leaderURL: 'https://ballotpedia.org/Phil_GiaQuinta',
    dateElected: '2006',
  },
  {
    districtName: 'Indiana House of Representatives District 81',
    leaderName: 'Martin Carbaugh',
    leaderURL: 'https://ballotpedia.org/Martin_Carbaugh',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 82',
    leaderName: 'Kyle Miller',
    leaderURL: 'https://ballotpedia.org/Kyle_Miller_(Indiana)',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 83',
    leaderName: 'Christopher Judy',
    leaderURL: 'https://ballotpedia.org/Christopher_N._Judy',
    dateElected: 'September 22, 2014',
  },
  {
    districtName: 'Indiana House of Representatives District 84',
    leaderName: 'Bob Morris',
    leaderURL: 'https://ballotpedia.org/Bob_Morris',
    dateElected: 'November 3, 2010',
  },
  {
    districtName: 'Indiana House of Representatives District 85',
    leaderName: 'David Heine',
    leaderURL: 'https://ballotpedia.org/Dave_Heine',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 86',
    leaderName: 'Edward DeLaney',
    leaderURL: 'https://ballotpedia.org/Edward_DeLaney',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 87',
    leaderName: 'Carey Hamilton',
    leaderURL: 'https://ballotpedia.org/Carey_Hamilton',
    dateElected: 'November 9, 2016',
  },
  {
    districtName: 'Indiana House of Representatives District 88',
    leaderName: 'Chris Jeter',
    leaderURL: 'https://ballotpedia.org/Chris_Jeter',
    dateElected: 'August 26, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 89',
    leaderName: 'Mitch Gore',
    leaderURL: 'https://ballotpedia.org/Mitch_Gore',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 90',
    leaderName: 'Andrew Ireland',
    leaderURL: 'https://ballotpedia.org/Andrew_Ireland',
    dateElected: 'November 6, 2024',
  },
  {
    districtName: 'Indiana House of Representatives District 91',
    leaderName: 'Robert Behning',
    leaderURL: 'https://ballotpedia.org/Robert_Behning',
    dateElected: '1992',
  },
  {
    districtName: 'Indiana House of Representatives District 92',
    leaderName: 'Renee Pack',
    leaderURL: 'https://ballotpedia.org/Renee_Pack',
    dateElected: 'November 4, 2020',
  },
  {
    districtName: 'Indiana House of Representatives District 93',
    leaderName: 'Julie McGuire',
    leaderURL: 'https://ballotpedia.org/Julie_McGuire',
    dateElected: 'November 9, 2022',
  },
  {
    districtName: 'Indiana House of Representatives District 94',
    leaderName: 'Cherrish Pryor',
    leaderURL: 'https://ballotpedia.org/Cherrish_Pryor',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 95',
    leaderName: 'John L. Bartlett',
    leaderURL:
      'https://ballotpedia.org/John_L._Bartlett_(Indiana_House_District_95_representative)',
    dateElected: '2008',
  },
  {
    districtName: 'Indiana House of Representatives District 96',
    leaderName: 'Gregory Porter',
    leaderURL: 'https://ballotpedia.org/Gregory_Porter',
    dateElected: '1992',
  },
  {
    districtName: 'Indiana House of Representatives District 97',
    leaderName: 'Justin Moed',
    leaderURL: 'https://ballotpedia.org/Justin_Moed',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 98',
    leaderName: 'Robin Shackleford',
    leaderURL: 'https://ballotpedia.org/Robin_Shackleford',
    dateElected: 'November 7, 2012',
  },
  {
    districtName: 'Indiana House of Representatives District 99',
    leaderName: 'Vanessa Summers',
    leaderURL: 'https://ballotpedia.org/Vanessa_Summers',
    dateElected: '1991',
  },
  {
    districtName: 'Indiana House of Representatives District 100',
    leaderName: 'Robert Johnson',
    leaderURL: 'https://ballotpedia.org/Robert_Blake_Johnson',
    dateElected: 'July 10, 2020',
  },
]
